### ISSUE TITLE
LCD outputting garbage

### ISSUE THREAD

**Issue by dazld** [rwaldron/johnny-five#326]
Arduino Leonardo
OSX 10.9.2
FTDI 32bit drivers

LCD1602A

Node 0.10.25

I can run and setup the LCD using the arduino IDE (1.5.6r2), everything appears to be fine. It's a simple circuit, pot for brightness, and 4bit controls wired up to the pins as in the example, 7-12.

When I try to output any text or commands to the LCD after installing firmata and running the J5 script, it either does nothing or just outputs garbage. Swapping back to the arduino IDE and running a sketch there works fine. 

I'm just using the eg/lcd.js example, nothing else for now.

Is this a known issue, am I doing something wrong...?

Looks like:

![screen shot 2014-04-21 at 18 44 57](https://cloud.githubusercontent.com/assets/201036/2756259/5c15edaa-c974-11e3-8c12-65e5b9ecee75.png)

**Comment by sephallen** [comment]
Sorry for bringing up an old issue, but was this ever resolved?
I have the same LCD screen and as with the OP is works fine in the Arduino IDE, but I just get a completely blank display with Johnny Five.
I've tried on an Uno and Mega, but both have the same results.

**Comment by rwaldron** [comment]
@sephallen are you using a parallel LCD (as shown in the image)? I find this is reproducible only when I have the LCD incorrectly wired, so that's the first thing to double check. Can you also paste the exact code that you're using?

**Comment by sephallen** [comment]
Yes, the LCD is almost identical.
The code I'm using with the Arduino IDE is the LiquidCrystal HelloWorld example which works perfectly.
The node code is as follows:

```javascript
var five = require("johnny-five"),
    board = new five.Board();
board.on("ready", function() {
    var lcd = new five.LCD({
        // LCD pin name  RS  EN  DB4 DB5 DB6 DB7
        // Arduino pin # 12  11   5   4  3  2
        pins: [ 12, 11, 5, 4, 3, 2 ],
        rows: 2,
        cols: 16
    });
    lcd.on("ready", function() {
        lcd.clear();
        lcd.setCursor(0,0);
        lcd.print("hello world");
    });
});
```

**Comment by rwaldron** [comment]
> The code I'm using with the Arduino IDE is the LiquidCrystal HelloWorld example which works perfectly.


Sorry for the dumb question: you made sure to upload StandardFirmata to the board before using the Johnny-Five program?

**Comment by sephallen** [comment]
Yes, of course.
I've ordered a *WH1602B* which I've read definitely works with Johnny-Five.
It should arrive in a couple of days, so I'll keep you updated.

**Comment by rwaldron** [comment]
Something that just occurred to me: `LCD` is no longer an EventEmitter (it's an output component and that never made sense). This means that if you're using the latest version of Johnny-Five, it should look like this: 

```js
var five = require("johnny-five");
var board = new five.Board();
board.on("ready", function() {
  var lcd = new five.LCD({
    // LCD pin name  RS  EN  DB4 DB5 DB6 DB7
    // Arduino pin # 12  11   5   4  3  2
    pins: [ 12, 11, 5, 4, 3, 2 ],
    rows: 2,
    cols: 16
  });
  lcd.clear().cursor(0, 0);
  lcd.print("hello world");
});
```

It's possible that an older example needs updating?

**Comment by sephallen** [comment]
Ah yes, that fixed it! I've looked at and tried multiple examples both in your documentation/wiki and around the net but this is the first time I've seen it written like this.

Thank you so much for the help and the great Johnny-Five!
I should have been more patient, I could have saved myself £10 by not buying another LCD!

**Comment by dazld** [comment]
I'll give this a go too.

**Comment by rwaldron** [comment]
> Ah yes, that fixed it! 

That's great news!!

> Thank you so much for the help and the great Johnny-Five!

My pleasure :)

> I should have been more patient, I could have saved myself £10 by not buying another LCD!

No way—now you can build something else!!

**Comment by dazld** [comment]
I finally managed to try this out - sadly the behaviour seen in the top post is still there. I'm going to chalk this up to dodgy hardware (despite working A1 with standard arduino IDE). I'd be happy to donate the LCD to a maintainer if anyone is interested in seeing why - but, regardless, can probably close this.

**Comment by rwaldron** [comment]
> (despite working A1 with standard arduino IDE)

Right and this should work with Johnny-Five. I've purchased many LCDs to ensure that they all work correctly and I'm at a loss this time. Can you share the code you're using?

**Comment by CaptEmulation** [comment]
I have been trying to get an LCD screen connected to a nitrogen service through johnny-five talking to an Arduino Yun via USB on Windows computer.  I've had no issue using many other pieces of johnny-five connected to an Arduino Yun, but I end up with garbage out of an LCD 49/50 times.  

Here is a sparkfun (https://www.sparkfun.com/products/255) 16x2 character LCD using the standard LiquidCrystal lib

![005](https://cloud.githubusercontent.com/assets/4467892/8888174/f307494e-3268-11e5-8a9c-961725750439.JPG)

Here is what I get when I run similar code using `five.LCD`:

![007](https://cloud.githubusercontent.com/assets/4467892/8888178/22221bdc-3269-11e5-9823-ecaf56ce67cf.JPG)

So I thought maybe an I2C LCD display like this http://www.sainsmart.com/sainsmart-iic-i2c-twi-serial-2004-20x4-lcd-module-shield-for-arduino-uno-mega-r3.html would work better so I wired it up and used the LiquidCrystal_I2C library on sainsmart page to do this:

![002](https://cloud.githubusercontent.com/assets/4467892/8888473/75112936-3274-11e5-839e-ff48055e0ccc.JPG)

I tried using johnny-five:

![008](https://cloud.githubusercontent.com/assets/4467892/8888478/91d6e272-3274-11e5-8b90-4c8c57aaf979.JPG)

I started looking at `lib/lcd.js` and made some timing changes to be more in-line with LiquidCrystal.cpp library for arduino.  During that time, I also used some code I wrote at work to implement the code without the use of `sleep`.  You can see the implementation _sans_ queue.js at https://github.com/rwaldron/johnny-five/compare/master...CaptEmulation:master.  I have at times been able to get the async/queued version to output the same garbage as your code. 

Here are my code snippits:
 - Arduino 16x2 parallel sketch https://gist.github.com/CaptEmulation/7844272599d929cd77ec
 - Johnny-five version https://gist.github.com/CaptEmulation/31c8049469200ea4c6db
 - Arduino 20x4 I2C sketch https://gist.github.com/CaptEmulation/24d26e784940315d641d
 - Johnny-five version: https://gist.github.com/CaptEmulation/7f52843b0404fb636618

 Anyway, I'm a little bit stumped at this point.  I have only gone through parts of comparing the implementations directly, and adjusting some the wait parameters.  The sketch code has much finer control over the timing and did some of the signaling differently.  I just don't know that I'll much more time to look at it, because I need to move on to other projects-- but this one has just been gnawing at me for a little while...  Obviously next, I'll be trying all of the johnny-five code on another machine entirely, and more  importantly an Ubuntu or Mac set up.

**Comment by rwaldron** [comment]
I wonder if there is an initial state issue with the expander chip that's on the board...?

**Comment by CaptEmulation** [comment]
## Thoughts

 - Operation logging and profiling
 - StandardFirmata => LcdFirmata

### Logging
A USB logger and a visualizer to map the differences in the implementations and adjust accordingly.  

I have a goal here of wanting to web visualize input/output from a johnny-five connected board, so a little side track of visualizing the StandardFirmata protocol sprinkled with instrumenting the Arduino library for the same would be a worthwhile trip and could even stay useful.

### LCD support in StandardFirmata
Operating under a presumption that a better signaling response would help.  Some of the timing in the standard library are at the ns level.

I early on considered implementing the LCD display logic on the Arduino through a new class of Firmata commands.   Later though, after looking at the Firmata code long enough, I instead tried a variety of performance improving tricks like 115K baud and toggling off input polling.   Implementing and running the logic within StandardFirmata is also an option.  

The device still has cycles and capacity for this approach.  It would also simplify the javascript logic, which can then focus on formatting and display and be operating with a stream style object representing the commands being generated in Firmata.

## Conclusion

I holding at "I'd like to take a look at it later".  

In regards to my other changes, the unit tests need to be adjusted to work asynchronously.  Also need to find an open source implementation of a callback queue...

**Comment by dazld** [comment]
Thought - if js runtimes cannot handle nanosecond timing, then would implementing a 'more accurate' queue as a native extension make sense? Is that even feasible..?

**Comment by soundanalogous** [comment]
One thing that may help here is adding a `PULSE_SEQUENCE` message to the Firmata protocol. It could be something like this:

```
0  START_SYSEX
1  SEND_PULSE (command ID TBD)
2  pin (0 - 127)
3  units (ms | us) | (start high | start low)
4  pulse1 length (bits 0 - 6)
5  pulse1 length (bits 7 - 13)
6  pulse1 length (bits 14 - 16)
7  pulse2 length (bits 0 - 6)
8  pulse2 length (bits 7 - 13)
9  pulse2 length (bits 14 - 16)
... as many pulses as necessary up to MAX_DATA_BYTES
N  END_SYSEX
```

To create the enablePulse function as seen [here](https://github.com/arduino/Arduino/blob/master/libraries/LiquidCrystal/src/LiquidCrystal.cpp#L303-L310), you'd then send this Firmata command:

```javascript
var data = [
  START_SYSEX,
  SEND_PULSE,
  0x10, // MS = 0x00, US = 0x10; start high = 0x01, start low = 0x00
  1,
  0,
  0,
  1,
  0,
  0,
  END_SYSEX
];
board.sendPulseSequence(new Buffer(data));
```

which would translate to the something like this on the Arduino:
```c++
case PULSE_SEQUENCE:
  byte pin = argv[1];
  byte edge = argv[2] & 0x0F;
  byte units = argv[2] & 0xF0;
  int pulseWidth = 0;

  for (byte i = 3; i < argc; i += 3) {
    pulseWidth = (argv[i + 2] << 14) | (argv[i + 1] << 7) | argv[i];
    digitalWrite(pin, edge);
    if (units && pulseWidth > 0) {
      delayMicroseconds(pulseWidth);
    else if (!units && pulseWidth > 0) {
      delay(pulseWidth);
    }
    edge != edge; // toggle the edge
  }
  break;
}
```

The last delay in `enablePulse` would be lost but it not part of the pulse and would be taken care of by latency if it's really short, or you'd need to delay before sending the next command from J5.

**Comment by CaptEmulation** [comment]
### Re: Frimata protocol proposal
I cry on the inside when I see blocking delays in code.  There could be implications if programmers choose long or wide pulses.  Of course, making it not blocking would be a much larger change to Firmata as the rest of the implementation would suddenly have timing concerns.  There's a trade off there between software complexity and CPU utilization.

### Code fix

That being said, you are missing a closing semi-colon in the Arduino code, above:

```
    if (units && pulseWidth > 0) {
      delayMicroseconds(pulseWidth);
    else if (!units && pulseWidth > 0) {
```
should be
```
    if (units && pulseWidth > 0) {
      delayMicroseconds(pulseWidth);
    } else if (!units && pulseWidth > 0) {
```

### Go Firmata!

That being said, I think support in Firmata is the way to go.  

### Look Ma, I made a logic analyzer instead of buying one

I tried to do this using a Phidget InterfaceKit 8/8/8, but I quickly realized they have entirely unusable DIO response (~125Hz).  Taking a different approach, I did all profiling in johnny-five implementation by looping back all of the outputs into unused Arduino inputs.  Using process.hrTime(), I am able to get some sub ms timing, which I outputted through a socket.io connection to a rickshaw/d3 graph running in browser.

![image](https://cloud.githubusercontent.com/assets/4467892/9028032/9d09ab58-3930-11e5-9809-d7209760a1a8.png)

One thing I noticed is that with the additional work of the logging, I began to see LCD output more frequently than before I started this venture.  Something closer to seeing LCD text one out four instead of one out of fifty.  Once the LCD came up correctly, I appeared to be able to write to it and it appeared to continue operating as expected.  That tidbit point to their being a timing issue with reset/start-up.

As expected from johnny-five implementation, the timing precision was about 1ms.  

### Make work

I may continue to refine this visualization, as well profiling implementations running on the embedded side.  I will be looking to explore what I can get running with Firmata, probably first simply running example LCD code and profiling-- assuming all of the blocking code within the Arduino LCD examples does not impede accurate profiling.  Anyway, I think what I really need is another Arduino to just do the profiling, instead of trying to do it all on one :-)

**Comment by soundanalogous** [comment]
Avoiding all blocking delays with Firmata is nearly impossible (but keeping them short is doable). Unfortunately, arduino doesn't ship with a good library for abstracting timer functionality (timer compare would be needed for generating accurate pulses) across all supported architectures. Even if it did it would be extremely difficult to balance the general I/O nature of Firmata with timer ISR handling. It would work better on some micros than others (more timers and faster clock = better). Anyway, a good trade off for now may be to only use blocking delays if a short delay is needed. For a longer delay, I could check the time on each iteration of the main loop ([this is how I handled delays for the Firmata stepper implementation](https://github.com/firmata/ConfigurableFirmata/blob/master/src/utility/FirmataStepper.cpp#L249-L260)). The duration of the delays would obviously be less accurate than using the timer compare functionality, but it would work across all supported architectures without conflict.

**Comment by rwaldron** [comment]
> One thing I noticed is that with the additional work of the logging, I began to see LCD output more frequently than before I started this venture. Something closer to seeing LCD text one out four instead of one out of fifty. Once the LCD came up correctly, I appeared to be able to write to it and it appeared to continue operating as expected. That tidbit point to their being a timing issue with reset/start-up.

This makes sense and I've experienced similar behavior in the past, but not reliably reproducible. I wonder if we can "fake" delays with calls to dummy functions that do some kind of operation that we can prove takes X amount of time to complete? I'm going to experiment.

**Comment by rexpie** [comment]
I have a piece of DFRobot [LCD](http://www.dfrobot.com/index.php?route=product/product&product_id=135&search=lcd&description=true#.VeCPjrR7wW8) 1602 display with IIC mounted on. 

I have tried to use the cpp version of the LCD library with no issue yet. But when I switched to johnny-five, I can't print more than 12 characters in a `print` statement, and I sometimes cannot get the LCD initialized proper( it prints partial message or garbage when I call print() the first time, but may work the next time I call `lcd.clean()` then `lcd.print("msg")`)

I can call

    print("01234567891");

works okay usually (sometimes garbage as well but can be cleaned and printed again).

But when I tried to call
    print("012345678901");
It prints garbage. Reproducible every time.

Here is the code I use
```javaScript
var five = require("johnny-five"),
  board, lcd;

board = new five.Board();

board.on("ready", function() {
    var lcd = new five.LCD({ 
        controller : "PCF8574",
        address   : 0x20 
        // this is the correct address, I checked the docs and the chip and tested with cpp
    });

    lcd.home();
    lcd.clear();

	
    lcd.print("012345678901"); 
    // prints out garbage, calling lcd.clear() does not work beyond this point
	
    this.repl.inject({
        lcd: lcd
    });
});
```

**Comment by rwaldron** [comment]
I have the v1 of that same LCD and it works exactly as expected. I just ordered this one to test with, so please be patient until that arrives—thanks!

**Comment by rexpie** [comment]
Thank you very much Rick. I tried to tweak the sleep timings in the LCD
module without any success.

2015-08-29 2:41 GMT+08:00 Rick Waldron <notifications@github.com>:

**Comment by rwaldron** [comment]
@rexpie I'll keep you posted and will let you know when the LCD arrives.

**Comment by rwaldron** [comment]
The LCD arrived! I will start working with it and report back as soon as I know more.

**Comment by rwaldron** [comment]
I was unable to reproduce, using the following: 

```js
var five = require("johnny-five");
var board = new five.Board();

board.on("ready", function() {
  var count = 0;
  var l = new five.LCD({
    controller: "PCF8574",
    address: 0x20
  });

  l.home();
  l.clear();
  l.print("012345678901");

  setInterval(function() {
    count++;

    if (count === 1) {
      l.clear();
      l.cursor(0, 0).print("0123456789012345");
    }

    if (count === 2) {
      l.clear();
      l.cursor(0, 0).print("0123456789012345");
      l.cursor(1, 0).print("0123456789012345");
    }

    if (count === 3) {
      l.clear();
      l.useChar("heart");
      l.cursor(0, 0).print("hello :heart:");
      l.blink();
      l.cursor(1, 0).print("Blinking? ");
    }

    if (count === 4) {
      l.clear();
      l.cursor(0, 0).print(" ".repeat(16));
      l.cursor(1, 0).print(" ".repeat(16));
    }

    if (count === 5) {
      l.clear();
      l.cursor(0, 0).print("*".repeat(16));
      l.cursor(1, 0).print("*".repeat(16));
    }
  }, 1000);

  this.repl.inject({
    clear: function() {
      l.clear();
      l.cursor(0, 0).print("cleared!");
    }
  });
});
```


![](https://dl.dropboxusercontent.com/u/3531958/nodebots/326.jpg)

https://youtu.be/cc9_1a4lkC8

**Comment by rexpie** [comment]
Thanks a lot Rick, I shall give it another try with your code and maybe
borrow another piece of LCD. Will let you know how it goes on Monday.

2015-09-04 4:35 GMT+08:00 Rick Waldron <notifications@github.com>:

**Comment by rexpie** [comment]
Hi Rick,

I got another piece of the same LCD, but still no luck. I used your code and it is not giving me correct output.

https://youtu.be/zPIQ1274JhI

Just found out that my board has a buggy behaviour with LCD. I switched to standard UNO board without built-in bluetooth chip and it works out just fine.

Well thank you very much Rick, turns out it is the chip fault. Would you PM me your paypal, that LCD is on me. :)

**Comment by rexpie** [comment]
However this made me think about why is a non-firmata LCD library working fine on that chip, but firmata client fails? Any insights about this Rick?

**Comment by rwaldron** [comment]
> Just found out that my board has a buggy behaviour with LCD. I switched to standard UNO board without built-in bluetooth chip and it works out just fine.

> However this made me think about why is a non-firmata LCD library working fine on that chip, but firmata client fails? Any insights about this Rick?

I'm not sure I follow? What board was giving you trouble? I thought you were using an Arduino UNO?

**Comment by rexpie** [comment]
>> Just found out that my board has a buggy behaviour with LCD. I switched to standard UNO board without built-in bluetooth chip and it works out just fine.

>> However this made me think about why is a non-firmata LCD library working fine on that chip, but firmata client fails? Any insights about this Rick?
> I'm not sure I follow? What board was giving you trouble? I thought you were using an Arduino UNO?

I am using a customised blueno board, which attaches a bluetooth chip to the serial pins. The bluetooth chip interferes with the serial communication and chops off the tails of long streams of data. That is the reason  for incorrectness when sending long strings to the LCD.

**Comment by rwaldron** [comment]
That explains a lot! Let's figure out a smart way to document this.

**Comment by rexpie** [comment]
Hi Rick,

It is more likely an issue related to firmata since it affects all firmata
clients, not specifically to j5. I am not sure where you want to put in the
documents. If you have a guide line as to which doc should we put this bit
of information in, I can write up something and give you a PR.

2015-09-09 0:00 GMT+08:00 Rick Waldron <notifications@github.com>:

**Comment by henricavalcante** [comment]
I got the same issue using Arduino Leonardo R3 and [LCD Keypad Shield](http://www.dx.com/p/2-6-lcd-keypad-shield-for-arduino-green-black-161359#.Vy34QJMrKRs)
![img_20160507_111039340](https://cloud.githubusercontent.com/assets/2352034/15092612/1fdd12a0-1445-11e6-956f-7fb41933863b.jpg)

Using LiquidCrystal hello world code like this
```cpp
// include the library code:
#include <LiquidCrystal.h>

// initialize the library with the numbers of the interface pins
LiquidCrystal lcd(8, 9, 4, 5, 6, 7);

void setup() {
  // set up the LCD's number of columns and rows:
  lcd.begin(16, 2);
  // Print a message to the LCD.
  lcd.print("hello, world!");
}

void loop() {
  // set the cursor to column 0, line 1
  // (note: line 1 is the second row, since counting begins with 0):
  lcd.setCursor(0, 1);
  // print the number of seconds since reset:
  lcd.print(millis() / 1000);
}
```
works fine
![img_20160507_103200516](https://cloud.githubusercontent.com/assets/2352034/15092619/63deda88-1445-11e6-9c9c-461e0cfb7a4d.jpg)

But using firmata + johnny-five solution
```js
var five = require("johnny-five"),board, lcd;
 
var board = new five.Board();
 
board.on("ready", function() {
 
  lcd = new five.LCD({
    pins: [8, 9, 4, 5, 6, 7],
    rows: 2,
    cols: 16
 
  });
 
  lcd.clear().print("Arduino");
  lcd.cursor(0, 1);
  lcd.print("lcd exammple");
 
 
  this.repl.inject({
    lcd: lcd
  });
});

```
 I got garbage displayed

![img_20160507_103100448](https://cloud.githubusercontent.com/assets/2352034/15092625/91aaeefc-1445-11e6-85e9-982cac5cb6c3.jpg)

**Comment by lyzadanger** [comment]
This issue has a long thread over a long time, so apologies if I'm repeating the obvious or anything.

I can consistently reproduce with a Tessel 2 and the SparkFun 3.3V LCD contained in the [Johnny Five Inventor's Kit](https://www.sparkfun.com/j5ik) using the following code:

```
const five = require('johnny-five');
const Tessel = require('tessel-io');

const board = new five.Board({
  io: new Tessel()
});

board.on('ready', () => {

  var lcd = new five.LCD({
    pins: ['a2', 'a3', 'a4', 'a5', 'a6', 'a7']
  });
  var displayCount = 0;

  setInterval(() => {
    displayCount++;
    lcd.clear();
    lcd.cursor(0, 0).print(displayCount + ': ' + Date.now());
  }, 1000);
});
```

The above usually craps out within 5 or 6 invocations; LCD is then unresponsive and full of garbage.

This can be fixed by either removing calls to `lcd.clear` or giving it some space:

```
const five = require('johnny-five');
const Tessel = require('tessel-io');

const board = new five.Board({
  io: new Tessel()
});

board.on('ready', () => {

  var lcd = new five.LCD({
    pins: ['a2', 'a3', 'a4', 'a5', 'a6', 'a7']
  });
  var displayCount = 0;

  setInterval(() => {
    displayCount++;
    lcd.clear();
    setTimeout(() => {
      lcd.cursor(0, 0).print(displayCount + ': ' + Date.now());
    }, 1000);
  }, 5000);
});
```

**Comment by rwaldron** [comment]
@lyzadanger I ran the clock code here: https://learn.sparkfun.com/tutorials/experiment-guide-for-the-johnny-five-inventors-kit/experiment-12-using-an-lcd-screen for over an hour without seeing garbled display. That program is not too different from yours, but doesn't have the call to `clear()`. I suspect that operation has some kind of time cost.

**Comment by fivdi** [comment]
@lyzadanger does it work if [this line in the sleep function in lcd.js](https://github.com/rwaldron/johnny-five/blob/master/lib/lcd.js#L15) is changed from:
```js
  while (Date.now() < start + ms) {}
```
to:
```js
  while (Date.now() < start + ms + 1) {}
```
The way the sleep function currently implemented, if asked to sleep for n milliseconds, it will sleep for more than n-1 milliseconds and less than n milliseconds for most calls. This can be seen with the following test program which calls sleep(2) once per second and outputs the number of seconds slept:
```js
function sleep(ms) {
  var start = Date.now();
  while (Date.now() < start + ms) {}
}

setInterval(function () {
  var time = time = process.hrtime();

  sleep(2);

  time = process.hrtime(time);
  console.log(time[0] + time[1] / 1E9);
}, 1000);
```
Here's some typical output from the test program:
```
0.001957897
0.001311549
0.001069937
0.002031697
0.001286914
0.001373007
0.001382486
0.001330975
0.001273685
0.001427173
0.001330768
```

**Comment by fivdi** [comment]
As mentioned [here](https://github.com/rwaldron/johnny-five/issues/326#issuecomment-42397724), the clear command takes 1.53 milliseconds to complete, so it's important to wait at least this long after sending a clear command to the LCD and before the next command is sent. The way the sleep function is currently implemented this will often not be the case.

**Comment by rwaldron** [comment]
@fivdi 👏🏽 Can you write a patch?

**Comment by fivdi** [comment]
See https://github.com/rwaldron/johnny-five/pull/1174

**Comment by lyzadanger** [comment]
This bad boy is fixed, right, by #1174? Ready for close?

**Comment by rwaldron** [comment]
Let's say that it is :)

**Comment by sallar** [comment]
I apologize if I'm being stupid, but this is still not fixed. Im trying to make it work with Spark Photon 3.3v with a 16x2 LCD. The only way to fix it is the setInterval example from @lyzadanger.

Am I doing something wrong? Is the merge published?
Thanks.

**Comment by rwaldron** [comment]
@sallar can you link to the _exact_ LCD device that you're using? Thanks

**Comment by sallar** [comment]
@rwaldron this is the one: [LCM1602C](http://www.datasheetcafe.com/lcm1602c-datasheet-pdf/)

**Comment by lyzadanger** [comment]
Alas, I haven't a Spark Photon so I can't do any hardware testing myself...

**Comment by rwaldron** [comment]
@sephallen this is likely a very different problem, based on the significant latency between the spark photon and the program host computer (which is sending the instructions over wifi, which result in digital writes on the spark photon). There is likely a timing and latency issue. The fact is that not all hardware component combinations will work together in exactly the same way.

**Comment by RazaZaidi2802** [comment]
Hi, I know I'm late here, I just created my account to post this comment. I'm too lazy to look up all the replies and see if this problem has been solved, but after having the same problem, scanning the internet, banging my head against the wall, cursing my miserable soldering skills for ruining the LCD, crying myself to sleep, I was tinkering around with the pins and **I tried separating the power sources of the back light and the LCDs power, i.e I used a separate 5v jack from my UNO to power 'A' of the LCD and the other 5v jack from my UNO to power 'VDD' of my LCD** and Lo n behold, the shit works! Just posting to save a life.
